name: "Prebuilt steps for build"
description: "Reusable steps for multiple jobs"
inputs:
   java_ver:
     required: true
     description: "Java version to install"
   ghc_ver:
     required: true
     description: "GHC version to install"
   github_ref:
     required: true
     description: "Git reference"
   os:
     required: true
     description: "Target OS"
   cache_path:
     required: false
     default: "~/.cabal/store"
     description: "Cache path"
   cabal_ver:
     required: false
     default: 3.14.1.1
     description: "GHC version to install"
   skip_install:
     required: false
     default: "false"
     description: "Skip installing common stuff (e.g. GHC, Cabal and Java). Useful for for Docker builds"
runs:
  using: "composite"
  steps:
    - name: Skip unreliable ghc 8.10.7 build on stable branch
      shell: bash
      if: inputs.ghc_ver == '8.10.7' && inputs.github_ref == 'refs/heads/stable'
      run: exit 0

    - name: Restore cached build
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.cache_path }}
          dist-newstyle
        key: ${{ inputs.os }}-ghc${{ inputs.ghc_ver }}-${{ hashFiles('cabal.project', 'simplex-chat.cabal') }}

    - name: Setup Haskell
      if: inputs.skip_install != 'true'
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ inputs.ghc_ver }}
        cabal-version: ${{ inputs.cabal_ver }}

    - name: Setup Java
      if: startsWith(inputs.github_ref, 'refs/tags/v') && inputs.skip_install != 'true'
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: ${{ inputs.java_ver }}
        cache: 'gradle'
